services:
  - type: web
    name: fastapi-app
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: |
      apt-get update && \
      if [ -f apt-packages ]; then
        while IFS= read -f package; do
          apt-get install -y "$package"
        done < apt-packages
      fi && \
      pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
